using System;
using System.Collections.Generic;
using System.Linq;
using Ceres.Editor;
using Ceres.Editor.Graph;
using Newtonsoft.Json;
using UnityEditor.Experimental.GraphView;
using UnityEngine.UIElements;
namespace NextGenDialogue.Graph.Editor
{
    [CustomNodeView(typeof(AIBakeModule))]
    public class AIBakeNodeView : EditorModuleNodeView
    {
        private string _lastSelection;
        
        private readonly Button _bakeDialogue;
        
        private readonly Button _autoGenerate;
        
        private readonly Button _loadLast;
        
        public AIBakeNodeView(Type type, CeresGraphView graphView): base(type, graphView)
        {
            mainContainer.Add(_bakeDialogue = new Button(GenerateCurrentSelection) { text = "Bake Dialogue" });
            mainContainer.Add(_autoGenerate = new Button(AutoGenerateFromSelection) { text = "Auto Generate Dialogue" });
            mainContainer.Add(_loadLast = new Button(LoadLastBakeSelections) { text = "Load Last Bake Selections" });
            _loadLast.SetEnabled(false);
        }
        
        private void LoadLastBakeSelections()
        {
            if (!string.IsNullOrEmpty(_lastSelection))
            {
                var lastSelections = JsonConvert.DeserializeObject<string[]>(_lastSelection);
                foreach (var selection in lastSelections)
                {
                    var node = GraphView.Query<UnityEditor.Experimental.GraphView.Node>().ToList().OfType<IDialogueNodeView>().FirstOrDefault(x => x.Guid == selection);
                    if (node != null) GraphView.AddToSelection(node.NodeElement);
                }
            }
        }
        
        private async void GenerateCurrentSelection()
        {
            _bakeDialogue.SetEnabled(false);
            _autoGenerate.SetEnabled(false);
            SaveCurrentSelection();
            await DialogueBaker.GenerateDialogue(GraphView);
            _bakeDialogue.SetEnabled(true);
            _autoGenerate.SetEnabled(true);
        }
        
        private async void AutoGenerateFromSelection()
        {
            _bakeDialogue.SetEnabled(false);
            _autoGenerate.SetEnabled(false);
            SaveCurrentSelection();
            await DialogueBaker.AutoGenerateDialogue(GraphView);
            _bakeDialogue.SetEnabled(true);
            _autoGenerate.SetEnabled(true);
        }
        
        private void SaveCurrentSelection()
        {
            var containers = GraphView.selection.OfType<ContainerNodeView>();
            _lastSelection = JsonConvert.SerializeObject(containers.Select(x => x.Guid).ToArray());
            _loadLast.SetEnabled(true);
        }
        
        protected override void OnRestore()
        {
            _lastSelection = ((AIBakeModule)NodeInstance).lastSelection;
            _loadLast.SetEnabled(!string.IsNullOrEmpty(_lastSelection));
        }
        
        protected override void OnSerialize()
        {
            ((AIBakeModule)NodeInstance).lastSelection = _lastSelection;
        }
    }
}
