using System.Collections.Generic;
using UnityEngine;
using System.Threading.Tasks;
using Kurisu.NGDS;
using System;
using Kurisu.NGDS.AI;
using System.Threading;
using System.Linq;
using UnityEditor;
using System.Text;
using Ceres.Editor.Graph;

namespace Kurisu.NGDT.Editor
{
    public class DialogueBaker
    {
        private const float maxWaitSeconds = 60.0f;
        private readonly AIPromptBuilder builder = new();
        /// <summary>
        /// Generate dialogue for selected container node by path from selection
        /// </summary>
        /// <param name="graphView"></param>
        /// <returns></returns>
        public static async Task GenerateDialogue(DialogueGraphView graphView)
        {
            var containers = graphView.selection.OfType<ContainerNode>().ToList();
            if (containers.Count == 0) return;
            var bakeContainer = containers.Last();
            containers.Remove(bakeContainer);
            float startVal = (float)EditorApplication.timeSinceStartup;
            var ct = graphView.GetCancellationTokenSource();
            DialogueBaker baker = new();
            var task = baker.Bake(containers, bakeContainer, ct.Token);
            while (!task.IsCompleted)
            {
                float slider = (float)(EditorApplication.timeSinceStartup - startVal) / maxWaitSeconds;
                EditorUtility.DisplayProgressBar("Wait to bake dialogue", "Waiting for a few seconds", slider);
                if (slider > 1)
                {
                    graphView.EditorWindow.ShowNotification(new GUIContent($"Dialogue baking is out of time, please check your internet!"));
                    ct.Cancel();
                    break;
                }
                await Task.Yield();
            }
            if (!task.IsCanceled && !task.Result)
            {
                graphView.EditorWindow.ShowNotification(new GUIContent($"Dialogue baking failed"));
            }
            EditorUtility.ClearProgressBar();
        }
        public static async Task AutoGenerateDialogue(DialogueGraphView graphView)
        {
            var containers = graphView.selection.OfType<ContainerNode>().ToList();
            if (containers.Count == 0) return;
            DialogueBaker baker = new();
            var bakeContainer = containers.Last();
            containers.Remove(bakeContainer);
            bakeContainer.TryGetModuleNode<AIBakeModule>(out ModuleNode aiBakeModule);
            int depth = aiBakeModule.GetFieldValue<int>("generateDepth");
            int option = aiBakeModule.GetFieldValue<int>("optionCount");
            float startVal = (float)EditorApplication.timeSinceStartup;
            var ct = graphView.GetCancellationTokenSource();
            int step = 0;
            var task = Generate(containers, bakeContainer, ct.Token, 0, depth);
            while (!task.IsCompleted)
            {
                float slider = (float)(EditorApplication.timeSinceStartup - startVal) / maxWaitSeconds;
                EditorUtility.DisplayProgressBar($"Wait to bake dialogue, step {step}", "Waiting for a few seconds", slider);
                if (slider > 1)
                {
                    graphView.EditorWindow.ShowNotification(new GUIContent($"Dialogue baking is out of time, please check your internet!"));
                    ct.Cancel();
                    break;
                }
                await Task.Yield();
            }
            if (!task.IsCanceled && !task.Result)
            {
                graphView.EditorWindow.ShowNotification(new GUIContent($"Dialogue baking failed"));
            }
            EditorUtility.ClearProgressBar();
            await Task.Delay(2);
            
            //Auto layout
            NodeAutoLayoutHelper.Layout(new DialogueTreeLayoutConvertor(graphView, bakeContainer));

            async Task<bool> Generate(IReadOnlyList<ContainerNode> containers, ContainerNode bakeContainer, CancellationToken ct, int currentDepth, int maxDepth)
            {
                step++;
                if (!await baker.Bake(containers, bakeContainer, ct)) return false;
                if (currentDepth >= maxDepth) return true;
                // Append current bake to last
                containers = new List<ContainerNode>(containers)
                {
                    bakeContainer
                };
                int count = bakeContainer is PieceContainer ? option : 1;
                for (int i = 0; i < count; i++)
                {
                    // Create next container
                    var node = graphView.CreateNextContainer(bakeContainer);
                    // Link nodes
                    graphView.ConnectContainerNodes(bakeContainer, node);
                    // Add bake module from script
                    // Random character
                    node.AddModuleNode(new AIBakeModule(depth, option));
                    if (!await Generate(containers, node, ct, currentDepth + 1, maxDepth)) return false;
                    node.RemoveModule<AIBakeModule>();
                }
                return true;
            }
        }
        /// <summary>
        /// Bake Dialogue Content in target container based on user's node selection
        /// </summary>
        /// <param name="containerNodes"></param>
        /// <param name="bakeContainerNode"></param>
        /// <param name="ct"></param>
        /// <returns></returns>
        public async Task<bool> Bake(IReadOnlyList<ContainerNode> containerNodes, ContainerNode bakeContainerNode, CancellationToken ct)
        {
            //Append user designed dialogue
            for (int i = 0; i < containerNodes.Count; i++)
            {
                AppendDialogue(containerNodes[i], builder);
            }
            if (bakeContainerNode is OptionContainer)
            {
                builder.ReverseRole();
            }
            //Generate dialogue from llm finally
            try
            {
                return await GenerateDialogue(bakeContainerNode, builder, ct);
            }
            catch (OperationCanceledException)
            {
                Debug.LogWarning($"[Dialogue Baker] Bake was cancelled");
                return false;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Dialogue Baker] {ex.Message}");
                return false;
            }
        }
        private static ILargeLanguageModel CreateLLM()
        {
            var setting = NextGenDialogueSetting.GetOrCreateSettings().AITurboSetting;
            return LLMFactory.CreateLLM(setting);
        }
        private static async Task<bool> GenerateDialogue(ContainerNode containerNode, AIPromptBuilder builder, CancellationToken ct)
        {
            try
            {
                var llm = CreateLLM();
                var response = (await llm.GenerateAsync(builder, ct)).Response;
                //Remove original module node since container can only contain one module for each type
                containerNode.RemoveModule<ContentModule>();
                //Create output module node
                containerNode.AddModuleNode(new ContentModule(response));
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Dialogue Baker] {ex}");
                return false;
            }
        }
        private static bool TrySetPrompt(ContainerNode containerNode, out string prompt)
        {
            prompt = null;
            if (containerNode.TryGetModuleNode<SystemPromptModule>(out ModuleNode promptModule))
            {
                prompt = promptModule.GetSharedStringValue("prompt");
                return true;
            }
            else if (containerNode.TryGetModuleNode<PromptPresetModule>(out ModuleNode promptPresetModule))
            {
                var text = promptPresetModule.GetSharedVariableValue<TextAsset>("prompt");
                if (text == null)
                {
                    Debug.LogError($"[Dialogue Baker] Prompt file is empty in {containerNode}");
                    return false;
                }
                prompt = text.text;
                return true;
            }
            else if (containerNode.TryGetModuleNode<CharacterPresetModule>(out ModuleNode presetModule))
            {
                var user_Name = presetModule.GetSharedStringValue("user_Name");
                var char_name = presetModule.GetSharedStringValue("char_name");
                var char_persona = presetModule.GetSharedStringValue("char_persona");
                var world_scenario = presetModule.GetSharedStringValue("world_scenario");
                prompt = ChatPromptHelper.ConstructPrompt(user_Name, char_name, char_persona, world_scenario);
                return true;
            }
            return false;
        }
        private void AppendDialogue(ContainerNode containerNode, AIPromptBuilder builder)
        {
            if (containerNode is DialogueContainer && TrySetPrompt(containerNode, out string prompt))
            {
                builder.Context = prompt;
                return;
            }
            MessageRole role = containerNode is OptionContainer ? MessageRole.User : MessageRole.Bot;
            if (!containerNode.TryGetModuleNode<ContentModule>(out ModuleNode contentModule)) return;
            string content = contentModule.GetSharedStringValue("content");
            builder.Append(role, content);
        }
        /// <summary>
        /// Generate a test bake content for editor test purpose
        /// </summary>
        /// <param name="containerNodes"></param>
        /// <param name="bakeContainerNode"></param>
        /// <returns></returns> <summary>
        public string Preview(IReadOnlyList<ContainerNode> containerNodes, ContainerNode bakeContainerNode)
        {
            StringBuilder stringBuilder = new();
            //Append user designed dialogue
            for (int i = 0; i < containerNodes.Count; i++)
            {
                AppendDialogue(containerNodes[i], builder);
            }
            if (bakeContainerNode is OptionContainer)
            {
                builder.ReverseRole();
            }
            stringBuilder.Append(builder.ToString());
            stringBuilder.Append($"{builder.BotName}:");
            return stringBuilder.ToString();
        }
    }
}
