using System.Collections.Generic;
using UnityEngine;
using System.Threading.Tasks;
using NextGenDialogue;
using System;
using NextGenDialogue.AI;
using System.Threading;
using System.Linq;
using UnityEditor;
using System.Text;
using Ceres.Editor.Graph;
using Cysharp.Threading.Tasks;
namespace NextGenDialogue.Graph.Editor
{
    public class DialogueBaker
    {
        private const float MaxWaitSeconds = 60.0f;
        
        private readonly AIPromptBuilder _builder = new();
        
        /// <summary>
        /// Generate dialogue for selected container node by path from selection
        /// </summary>
        /// <param name="graphView"></param>
        /// <returns></returns>
        public static async Task GenerateDialogue(DialogueGraphView graphView)
        {
            var containers = graphView.selection.OfType<ContainerNodeView>().ToList();
            if (containers.Count == 0) return;
            var bakeContainer = containers.Last();
            containers.Remove(bakeContainer);
            float startVal = (float)EditorApplication.timeSinceStartup;
            var ct = graphView.GetCancellationTokenSource();
            DialogueBaker baker = new();
            var task = baker.Bake(containers, bakeContainer, ct.Token);
            while (!task.IsCompleted)
            {
                float slider = (float)(EditorApplication.timeSinceStartup - startVal) / MaxWaitSeconds;
                EditorUtility.DisplayProgressBar("Wait to bake dialogue", "Waiting for a few seconds", slider);
                if (slider > 1)
                {
                    graphView.EditorWindow.ShowNotification(new GUIContent($"Dialogue baking is out of time, please check your internet!"));
                    ct.Cancel();
                    break;
                }
                await UniTask.Yield(cancellationToken:ct.Token);
            }
            if (!task.IsCanceled && !task.Result)
            {
                graphView.EditorWindow.ShowNotification(new GUIContent($"Dialogue baking failed"));
            }
            EditorUtility.ClearProgressBar();
        }
        public static async UniTask AutoGenerateDialogue(DialogueGraphView graphView)
        {
            var containers = graphView.selection.OfType<ContainerNodeView>().ToList();
            if (containers.Count == 0) return;
            DialogueBaker baker = new();
            var bakeContainer = containers.Last();
            containers.Remove(bakeContainer);
            bakeContainer.TryGetModuleNode<AIBakeModule>(out ModuleNodeView aiBakeModule);
            int depth = aiBakeModule.GetFieldValue<int>("generateDepth");
            int option = aiBakeModule.GetFieldValue<int>("optionCount");
            float startVal = (float)EditorApplication.timeSinceStartup;
            var ct = graphView.GetCancellationTokenSource();
            int step = 0;
            var task = Generate(containers, bakeContainer, ct.Token, 0, depth);
            while (!task.IsCompleted)
            {
                float slider = (float)(EditorApplication.timeSinceStartup - startVal) / MaxWaitSeconds;
                EditorUtility.DisplayProgressBar($"Wait to bake dialogue, step {step}", "Waiting for a few seconds", slider);
                if (slider > 1)
                {
                    graphView.EditorWindow.ShowNotification(new GUIContent($"Dialogue baking is out of time, please check your internet!"));
                    ct.Cancel();
                    break;
                }
                await UniTask.Yield(cancellationToken:ct.Token);
            }
            if (!task.IsCanceled && !task.Result)
            {
                graphView.EditorWindow.ShowNotification(new GUIContent($"Dialogue baking failed"));
            }
            EditorUtility.ClearProgressBar();
            await UniTask.WaitForSeconds(2, cancellationToken:ct.Token);
            
            // Auto layout
            new DialogueTreeLayoutConvertor(graphView, bakeContainer).Layout();

            async Task<bool> Generate(IReadOnlyList<ContainerNodeView> inContainers, ContainerNodeView inBakeContainer, CancellationToken ct, int currentDepth, int maxDepth)
            {
                step++;
                if (!await baker.Bake(inContainers, inBakeContainer, ct)) return false;
                if (currentDepth >= maxDepth) return true;
                // Append current bake to last
                inContainers = new List<ContainerNodeView>(inContainers)
                {
                    inBakeContainer
                };
                int count = inBakeContainer is PieceContainerView ? option : 1;
                for (int i = 0; i < count; i++)
                {
                    // Create next container
                    var node = graphView.CreateNextContainer(inBakeContainer);
                    // Link nodes
                    graphView.ConnectContainerNodes(inBakeContainer, node);
                    // Add bake module from script
                    // Random character
                    node.AddModuleNode(new AIBakeModule(depth, option));
                    if (!await Generate(inContainers, node, ct, currentDepth + 1, maxDepth)) return false;
                    node.RemoveModule<AIBakeModule>();
                }
                return true;
            }
        }
        
        /// <summary>
        /// Bake Dialogue Content in target container based on user's node selection
        /// </summary>
        /// <param name="containerNodes"></param>
        /// <param name="bakeContainerNodeView"></param>
        /// <param name="ct"></param>
        /// <returns></returns>
        public async Task<bool> Bake(IReadOnlyList<ContainerNodeView> containerNodes, ContainerNodeView bakeContainerNodeView, CancellationToken ct)
        {
            // Append user designed dialogue
            for (int i = 0; i < containerNodes.Count; i++)
            {
                AppendDialogue(containerNodes[i], _builder);
            }
            if (bakeContainerNodeView is OptionContainerView)
            {
                _builder.ReverseRole();
            }
            // Generate dialogue from llm finally
            try
            {
                return await GenerateDialogue(bakeContainerNodeView, _builder, ct);
            }
            catch (OperationCanceledException)
            {
                Debug.LogWarning($"[Dialogue Baker] Bake was cancelled");
                return false;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Dialogue Baker] {ex.Message}");
                return false;
            }
        }
        
        private static ILargeLanguageModel CreateLLM()
        {
            var setting = NextGenDialogueSettings.Get().AITurboSetting;
            return LLMFactory.CreateLLM(setting);
        }
        
        private static async UniTask<bool> GenerateDialogue(ContainerNodeView containerNodeView, AIPromptBuilder builder, CancellationToken ct)
        {
            try
            {
                var llm = CreateLLM();
                var response = (await llm.GenerateAsync(builder, ct)).Response;
                //Remove original module node since container can only contain one module for each type
                containerNodeView.RemoveModule<ContentModule>();
                //Create output module node
                containerNodeView.AddModuleNode(new ContentModule(response));
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[Dialogue Baker] {ex}");
                return false;
            }
        }
        private static bool TrySetPrompt(ContainerNodeView containerNodeView, out string prompt)
        {
            prompt = null;
            if (containerNodeView.TryGetModuleNode<SystemPromptModule>(out ModuleNodeView promptModule))
            {
                prompt = promptModule.GetSharedStringValue("prompt");
                return true;
            }

            if (containerNodeView.TryGetModuleNode<PromptPresetModule>(out ModuleNodeView promptPresetModule))
            {
                var text = promptPresetModule.GetSharedVariableValue<TextAsset>("prompt");
                if (text == null)
                {
                    Debug.LogError($"[Dialogue Baker] Prompt file is empty in {containerNodeView}");
                    return false;
                }
                prompt = text.text;
                return true;
            }
            
            if (containerNodeView.TryGetModuleNode<CharacterPresetModule>(out ModuleNodeView presetModule))
            {
                var user_Name = presetModule.GetSharedStringValue("user_Name");
                var char_name = presetModule.GetSharedStringValue("char_name");
                var char_persona = presetModule.GetSharedStringValue("char_persona");
                var world_scenario = presetModule.GetSharedStringValue("world_scenario");
                prompt = ChatPromptHelper.ConstructPrompt(user_Name, char_name, char_persona, world_scenario);
                return true;
            }

            return false;
        }
        
        private void AppendDialogue(ContainerNodeView containerNodeView, AIPromptBuilder builder)
        {
            if (containerNodeView is DialogueContainerView && TrySetPrompt(containerNodeView, out string prompt))
            {
                builder.Context = prompt;
                return;
            }
            MessageRole role = containerNodeView is OptionContainerView ? MessageRole.User : MessageRole.Bot;
            if (!containerNodeView.TryGetModuleNode<ContentModule>(out ModuleNodeView contentModule)) return;
            string content = contentModule.GetSharedStringValue("content");
            builder.Append(role, content);
        }
        
        /// <summary>
        /// Generate a test bake content for editor test purpose
        /// </summary>
        /// <param name="containerNodes"></param>
        /// <param name="bakeContainerNodeView"></param>
        /// <returns></returns> <summary>
        public string Preview(IReadOnlyList<ContainerNodeView> containerNodes, ContainerNodeView bakeContainerNodeView)
        {
            StringBuilder stringBuilder = new();
            //Append user designed dialogue
            for (int i = 0; i < containerNodes.Count; i++)
            {
                AppendDialogue(containerNodes[i], _builder);
            }
            if (bakeContainerNodeView is OptionContainerView)
            {
                _builder.ReverseRole();
            }
            stringBuilder.Append(_builder);
            stringBuilder.Append($"{_builder.BotName}:");
            return stringBuilder.ToString();
        }
    }
}
